FROM node:16.14.2-alpine3.15
WORKDIR /usr/app
COPY /build /usr/app/build
RUN npm install -g serve
EXPOSE 3000
#CMD "serve -s build"
#CMD npm start
#RUN serve -s build

#FROM httpd:alpine3.15
#COPY /build/. /usr/local/apache2/htdocs/
#EXPOSE 80