FROM openjdk:19-jdk-alpine3.15
WORKDIR /api-backend
EXPOSE 8080
COPY target/digital-cars-0.0.1-SNAPSHOT.jar /api-backend/app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

##docker run -it -m 256M --cpus="0.25" 831810ba0bb3

##docker run -it -m 512M --cpus="0.25" 73c30a5d10b3